# Generated by Django 2.0.8 on 2019-01-15 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 4, 0, 53, 541979, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
