# Generated by Django 2.0.8 on 2019-01-18 23:45

from django.db import migrations, models
from apps.blog.models import create_slug


def update_slug(apps, schema_editor):
    Blog = apps.get_model("blog", "Blog")

    for instance in Blog.objects.all():
        if not instance.slug:
            instance.slug = create_slug(instance)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_read_time'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),

        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
