# Generated by Django 2.0.8 on 2019-01-19 00:33

from django.db import migrations, models
from apps.blog.models import create_slug


def update_slug(apps, schema_editor):
    Blog = apps.get_model("blog", "Blog")

    for instance in Blog.objects.all():
        if not instance.slug:
            instance.slug = create_slug(instance)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_slug'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
