# Generated by Django 2.0.8 on 2019-01-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180920_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
